apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "single-cell.fullname" . }}
  labels:
{{ include "single-cell.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "single-cell.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "single-cell.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end}}
      containers:
        {{ if .Values.cellranger }}
        - name: cellranger
          image: {{ .Values.cellranger.image }}
          {{ if .Values.cellranger.command }}
          command:
          {{- range .Values.cellranger.command }}
          - {{ . }}
          {{- end }}
          {{ end }}
          stdin: {{ .Values.cellranger.stdin }}
          volumeMounts:
            - name: cellranger
              mountPath: /tmp/streamflow
          imagePullPolicy: {{ .Values.cellranger.pullPolicy }}
          resources:
            {{- toYaml .Values.cellranger.resources | nindent 12 }}
        {{ end }}
        {{ if .Values.renvironment }}
        - name: r-environment
          image: {{ .Values.renvironment.image }}
          {{ if .Values.renvironment.command }}
          command:
          {{- range .Values.renvironment.command }}
          - {{ . }}
          {{- end }}
          {{ end }}
          stdin: {{ .Values.cellranger.stdin }}
          imagePullPolicy: {{ .Values.renvironment.pullPolicy }}
          resources:
            {{- toYaml .Values.renvironment.resources | nindent 12 }}
        {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{ if .Values.cellranger }}
  volumeClaimTemplates:
    - metadata:
        name: cellranger
      spec:
        accessModes:
          - {{ .Values.cellranger.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.cellranger.persistence.capacity | quote }}
  {{ end }}