#!/bin/bash
CELLRANGER_VERSION=${1:-"3.1.0"}

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build \
    --build-arg CELLRANGER_VERSION=${CELLRANGER_VERSION} \
    -t gitlab.c3s.unito.it:5000/alpha/single-cell-pipeline:cellranger \
    ${SCRIPT_DIRECTORY}
