#!/bin/sh

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker build \
    -t gitlab.c3s.unito.it:5000/alpha/single-cell-pipeline:r-environment \
    ${SCRIPT_DIRECTORY}
